name: beltei_portal
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^14.0.0
  google_fonts: ^6.2.1
  percent_indicator: ^4.2.3
  fl_chart: ^0.69.0
  table_calendar: ^3.1.2
  intl: ^0.20.2
  supabase_flutter: ^2.8.4
  flutter_riverpod: ^2.6.1
  flutter_dotenv: ^5.2.1
  pdf: ^3.10.8
  excel: ^4.0.6
  image_picker: ^1.1.2
  file_picker: ^8.0.0
  shared_preferences: ^2.3.3
  printing: ^5.14.3
  path_provider: ^2.1.6
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - .env
